feat: linkbutton with linknext
pedrohbl03/scrummy-app pull request #18
Opened 2022-12-29 18:45 UTC by femacedogomes

in this branch i created a link component based on Next/Link HOC.
task: https://www.notion.so/028386dd8cc04ffeaa06931d912bd0fc?v=b8d42189aed746d8a0a716c781c8d731&p=1b5a1e5dce1a46bfb27c3fbced3374a7&pm=s

2022-12-30 15:25 UTC, pedrohbl03 commented on src/components/atoms/Link/index.tsx
> +            ' text-scrummyOrange-500 decoration-scrummyOrange-500 ':
i invite you to think this using other props;

**example:** bgColor, text Color, size, etc...

if we use a unique prop called styled, this component has a very coupled style.

2022-12-30 15:27 UTC, pedrohbl03 requested changes
see this to better practice in dumb components;

2023-01-02 19:08 UTC, renanpontez approved these changes

2023-01-02 21:09 UTC, pedrohbl03 commented on src/components/atoms/Link/index.tsx
> +  href,
it's good add more props.
Example `externalLink` and if true, add a external icon and target blank in `<a>` tag.

2023-01-03 19:09 UTC, pedrohbl03 approved these changes
GOOOOOOD!

2023-01-03 19:10 UTC, merged