feat: login page
pedrohbl03/scrummy-app pull request #19
Opened 2023-01-11 14:37 UTC by femacedogomes

Login Page screen with no API integration. Still need's to improve the mobile screen version.

https://www.notion.so/028386dd8cc04ffeaa06931d912bd0fc?v=b8d42189aed746d8a0a716c781c8d731&p=13e255df270a4b81a6c7d21e384afe8a&pm=s

2023-01-12 21:24 UTC, pedrohbl03 requested changes

2023-01-12 21:24 UTC, pedrohbl03 commented on src/components/atoms/Input/index.tsx
> +          'align-middle h-[46px] w-full rounded-lg bg-dark-100 text-gray-100 focus:outline-none placeholder:text-gray-500',
add a new styles to change default style by google for autofill values. 

We can make this in tailwind 3+ using "autofill" pseudo-element.

look this exemple:

`"autofill:bg-transparent"`

you can check more about this in: [Tailwind Autofill Docs](https://tailwindcss.com/docs/hover-focus-and-other-states#autofill
)

2023-01-12 21:24 UTC, pedrohbl03 commented on src/pages/auth/login.tsx
> +  const handleSubmit = (e: { preventDefault: () => void }) => {
```suggestion
  const handleSubmit = (e: React.ChangeEvent<HTMLInputElement>) => {
```
We can make this ?

2023-01-13 10:27 UTC, femacedogomes commented on src/pages/auth/login.tsx
> +  const handleSubmit = (e: { preventDefault: () => void }) => {
maded

2023-01-16 19:32 UTC, renanpontez approved these changes
Great work!

2023-01-16 19:59 UTC, merged